# Generated by Django 6.0.4 on 2026-07-15 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICreditPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.PositiveIntegerField()),
                ('retail_price_bdt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'credits'],
            },
        ),
        migrations.CreateModel(
            name='BKashAgreement',
            fields=[
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_identifier', models.CharField(help_text='e.g. customer phone or user id', max_length=100)),
                ('agreement_id', models.CharField(max_length=255, unique=True)),
                ('payer_reference', models.CharField(max_length=100)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantAPIToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_prefix', models.CharField(max_length=12)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundWebhook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='HTTPS endpoint that receives events.', max_length=500)),
                ('secret', models.CharField(help_text='HMAC-SHA256 signing secret. Shown once on creation.', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('FAILED', 'Disabled (Repeated Failures)')], default='ACTIVE', max_length=10)),
                ('subscribed_events', models.JSONField(default=list)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('BKASH', 'bKash (Tokenized)'), ('NAGAD', 'Nagad'), ('SSLCOMMERZ', 'SSLCommerz'), ('PORTPOS', 'PortPOS'), ('POLAR', 'Polar'), ('STRIPE', 'Stripe'), ('MANUAL', 'Manual / Bank Transfer')], max_length=20)),
                ('credentials_encrypted', models.TextField(blank=True, help_text='JSON-encoded gateway credentials stored encrypted. Use billing.services.gateway.set_gateway_credentials() to write — never write directly.')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Merchant can disable a gateway without deleting its credentials.')),
                ('is_test_mode', models.BooleanField(default=False, help_text='Toggles the gateway SDK to its sandbox environment.')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('SSLCOMMERZ', 'SSLCommerz / Card'), ('PORTPOS', 'PortPOS'), ('POLAR', 'Polar'), ('STRIPE', 'Stripe')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('fee_payer', models.CharField(choices=[('MERCHANT', 'Merchant absorbs fee'), ('CUSTOMER', 'Customer pays fee')], default='MERCHANT', help_text='Defaults to merchant per global_business_rules_and_limits.md §3.', max_length=10)),
                ('custom_instructions', models.TextField(blank=True, help_text="e.g. 'Send to bKash 01XXXXXXXXX and paste your TxnID below.'")),
                ('requires_transaction_id', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(blank=True, help_text='Storefront order UUID', null=True)),
                ('subscription_id', models.UUIDField(blank=True, help_text='ShopSubscription UUID', null=True)),
                ('gateway', models.CharField(choices=[('BKASH', 'bKash (Tokenized)'), ('NAGAD', 'Nagad'), ('SSLCOMMERZ', 'SSLCommerz'), ('PORTPOS', 'PortPOS'), ('POLAR', 'Polar'), ('STRIPE', 'Stripe'), ('MANUAL', 'Manual / Bank Transfer')], max_length=20)),
                ('external_transaction_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('status', models.CharField(default='INITIATED', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField(blank=True)),
                ('external_refund_id', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic — 990 ৳/mo'), ('PRO', 'Pro — 1,990 ৳/mo'), ('BUSINESS', 'Business — 4,990 ৳/mo'), ('CUSTOM', 'Custom / Staff Plan')], default='FREE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRACE', 'Grace Period'), ('SUSPENDED', 'Suspended'), ('COMPLIANCE_LOCK', 'Compliance Lock'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('grace_period_until', models.DateTimeField(blank=True, help_text='If set, shop is in grace period until this datetime. After this, status → SUSPENDED.', null=True)),
                ('last_paid_at', models.DateTimeField(blank=True, null=True)),
                ('is_billing_exempt', models.BooleanField(default=False, help_text='Admin-only. Completely skips billing enforcement for test/staff shops.')),
                ('admin_note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AICreditTopUp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits_purchased', models.PositiveIntegerField()),
                ('amount_paid_bdt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.aicreditpackage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
