# Generated by Django 6.0.4 on 2026-07-14 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantapitoken',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantapitoken',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='outboundwebhook',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_webhooks', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='aicredittopup',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_topup_record', to='billing.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='billing.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='shopsubscription',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='merchantapitoken',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop'], name='billing_apitoken_shop_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundwebhook',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'status'], name='billing_wh_shop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewayconfig',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'is_active'], name='billing_gw_shop_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentgatewayconfig',
            unique_together={('shop', 'gateway')},
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'is_enabled'], name='billing_pm_shop_enabled_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('shop', 'method')},
        ),
        migrations.AddIndex(
            model_name='shopsubscription',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop'], name='billing_sub_shop_active_idx'),
        ),
        migrations.AddIndex(
            model_name='shopsubscription',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['status'], name='billing_sub_status_active_idx'),
        ),
    ]
