# Generated by GitHub Copilot on 2026-05-01

from django.db import migrations


def rename_portwallet_to_portpos(apps, schema_editor):
    PaymentMethod = apps.get_model("billing", "PaymentMethod")

    portwallet_qs = PaymentMethod.objects.filter(method="PORTWALLET")
    for portwallet in portwallet_qs.iterator():
        conflict = PaymentMethod.objects.filter(
            shop_id=portwallet.shop_id,
            method="PORTPOS",
        ).first()

        if conflict:
            portwallet.delete()
            continue

        portwallet.method = "PORTPOS"
        portwallet.save(update_fields=["method"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_aicreditpackage_aicredittopup"),
    ]

    operations = [
        migrations.RunPython(rename_portwallet_to_portpos, noop_reverse),
    ]
