# Generated by Django 6.0.4 on 2026-05-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rename_portwallet_to_portpos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='gateway',
            field=models.CharField(choices=[('BKASH', 'bKash (Tokenized)'), ('NAGAD', 'Nagad'), ('SSLCOMMERZ', 'SSLCommerz'), ('PORTPOS', 'PortPOS'), ('POLAR', 'Polar'), ('STRIPE', 'Stripe'), ('MANUAL', 'Manual / Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('SSLCOMMERZ', 'SSLCommerz / Card'), ('PORTPOS', 'PortPOS'), ('POLAR', 'Polar'), ('STRIPE', 'Stripe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('BKASH', 'bKash (Tokenized)'), ('NAGAD', 'Nagad'), ('SSLCOMMERZ', 'SSLCommerz'), ('PORTPOS', 'PortPOS'), ('POLAR', 'Polar'), ('STRIPE', 'Stripe'), ('MANUAL', 'Manual / Bank Transfer')], max_length=20),
        ),
    ]
