# Generated by Django 6.0.4 on 2026-07-15 07:52

from django.db import migrations

def create_rls_policies(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for model in apps.get_models():
            if hasattr(model, 'tenant_id') and hasattr(model._meta, 'db_table') and model._meta.managed:
                table = model._meta.db_table
                field_names = [f.name for f in model._meta.get_fields()]
                if 'tenant_id' in field_names:
                    cursor.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY;')
                    cursor.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY;')
                    
                    policy_sql = f'''
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_policies 
                            WHERE tablename = '{table}' AND policyname = 'tenant_isolation_policy'
                        ) THEN
                            CREATE POLICY tenant_isolation_policy ON "{table}"
                            FOR ALL
                            USING (
                                tenant_id::text = current_setting('app.current_shop_id', true)
                                OR current_setting('app.bypass_rls', true) = 'on'
                            );
                        END IF;
                    END
                    $$;
                    '''
                    cursor.execute(policy_sql)

def reverse_rls_policies(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for model in apps.get_models():
            if hasattr(model, 'tenant_id') and hasattr(model._meta, 'db_table') and model._meta.managed:
                table = model._meta.db_table
                field_names = [f.name for f in model._meta.get_fields()]
                if 'tenant_id' in field_names:
                    cursor.execute(f'DROP POLICY IF EXISTS tenant_isolation_policy ON "{table}";')
                    cursor.execute(f'ALTER TABLE "{table}" NO FORCE ROW LEVEL SECURITY;')
                    cursor.execute(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY;')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_setup_extensions'),
    ]

    operations = [
        migrations.RunPython(create_rls_policies, reverse_rls_policies),
    ]

