# Generated by Django 6.0.4 on 2026-07-15 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIdentitySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_phone', models.CharField(blank=True, max_length=32)),
                ('phone_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_address', models.TextField(blank=True)),
                ('address_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('channel', models.CharField(blank=True, max_length=20)),
                ('channel_identity', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('display_phone', models.CharField(blank=True, max_length=32)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('display_address', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point_type', models.CharField(choices=[('PHONE', 'Phone'), ('ADDRESS', 'Address'), ('FACEBOOK', 'Facebook'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], db_index=True, max_length=20)),
                ('value_hash', models.CharField(db_index=True, max_length=64)),
                ('value_suffix', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('display_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['point_type', 'value_hash'], name='cp_type_hash_idx'), models.Index(fields=['point_type', 'value_suffix'], name='cp_type_suffix_idx')],
                'constraints': [models.UniqueConstraint(fields=('point_type', 'value_hash'), name='uq_contact_point_type_hash')],
            },
        ),
        migrations.CreateModel(
            name='ContactPointLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_reason', models.CharField(choices=[('CO_OCCURRED_IN_ORDER', 'Co-occurred in Order')], default='CO_OCCURRED_IN_ORDER', max_length=30)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_source', to='identity.contactpoint')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_target', to='identity.contactpoint')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContactPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('first_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to='identity.contactpoint')),
            ],
        ),
    ]
