# Generated by Django 6.0.4 on 2026-07-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('orders', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontactpoint',
            name='customer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='shops.customerprofile'),
        ),
        migrations.AddField(
            model_name='orderidentitysnapshot',
            name='address_contact_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.contactpoint'),
        ),
        migrations.AddField(
            model_name='orderidentitysnapshot',
            name='channel_contact_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.contactpoint'),
        ),
        migrations.AddField(
            model_name='orderidentitysnapshot',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_snapshot', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderidentitysnapshot',
            name='phone_contact_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.contactpoint'),
        ),
        migrations.AddIndex(
            model_name='contactpointlink',
            index=models.Index(fields=['source', 'target'], name='cpl_source_target_idx'),
        ),
        migrations.AddIndex(
            model_name='contactpointlink',
            index=models.Index(fields=['target'], name='cpl_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactpointlink',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'link_reason'), name='uq_contact_point_link'),
        ),
        migrations.AddConstraint(
            model_name='contactpointlink',
            constraint=models.CheckConstraint(condition=models.Q(('source__lt', models.F('target'))), name='ck_contact_point_link_canonical_order'),
        ),
        migrations.AddIndex(
            model_name='customercontactpoint',
            index=models.Index(fields=['contact_point'], name='ccp_contact_point_idx'),
        ),
        migrations.AddIndex(
            model_name='customercontactpoint',
            index=models.Index(fields=['customer_profile'], name='ccp_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercontactpoint',
            constraint=models.UniqueConstraint(fields=('customer_profile', 'contact_point'), name='uq_customer_contact_point'),
        ),
    ]
