# Generated by Django 6.0.4 on 2026-07-17 05:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_unify_phone_hashing'),
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='identity.household')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='identity.person')),
                ('primary_phone_cp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.contactpoint')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelActor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('FACEBOOK', 'Facebook Messenger'), ('WHATSAPP', 'WhatsApp'), ('WEB_WIDGET', 'Web Widget')], db_index=True, max_length=20)),
                ('channel_identity', models.CharField(db_index=True, max_length=255)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('phone_cp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.contactpoint')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_actors', to='shops.shop')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to='identity.person')),
            ],
        ),
        migrations.AddField(
            model_name='contactpoint',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_points', to='identity.person'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['merged_into'], name='person_merged_into_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['household'], name='person_household_idx'),
        ),
        migrations.AddIndex(
            model_name='channelactor',
            index=models.Index(fields=['person'], name='channel_actor_person_idx'),
        ),
        migrations.AddIndex(
            model_name='channelactor',
            index=models.Index(fields=['shop', 'channel', 'channel_identity'], name='channel_actor_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelactor',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('shop', 'channel', 'channel_identity'), name='uq_channel_actor_shop_channel_identity'),
        ),
    ]
