# Generated by Django 6.0.4 on 2026-07-17 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_household_person_channelactor_contactpoint_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonBehavioralAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orders_placed', models.PositiveIntegerField(default=0)),
                ('orders_delivered', models.PositiveIntegerField(default=0)),
                ('orders_rto', models.PositiveIntegerField(default=0)),
                ('orders_cancelled', models.PositiveIntegerField(default=0)),
                ('courier_success_rate', models.FloatField(blank=True, null=True)),
                ('courier_rate_updated_at', models.DateTimeField(blank=True, null=True)),
                ('first_order_at', models.DateTimeField(blank=True, null=True)),
                ('last_order_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_aggregate', to='identity.person')),
            ],
            options={
                'indexes': [models.Index(fields=['person'], name='pba_person_idx')],
            },
        ),
    ]
