# Generated by Django 6.0.4 on 2026-07-14 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateclick',
            name='referrer_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_clicks', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_info', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['referrer_shop', 'created_at'], name='affiliates__referre_623f92_idx'),
        ),
    ]
