# Generated by Django 6.0.4 on 2026-07-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('marketing', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaadaccount',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_accounts', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='metaadcampaign',
            name='ad_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='marketing.metaadaccount'),
        ),
        migrations.AddField(
            model_name='metaadcampaign',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='metauseraccount',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_user_account', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='productsocialpostlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_post_logs', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productsocialpostlog',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_post_logs', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='productsocialpostlog',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_logs', to='marketing.socialconnection'),
        ),
        migrations.AddIndex(
            model_name='metaadaccount',
            index=models.Index(fields=['shop', 'is_active'], name='marketing_m_shop_id_2e6bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconnection',
            index=models.Index(fields=['shop', 'provider', 'status'], name='socconn_shop_prov_status_ix'),
        ),
        migrations.AddConstraint(
            model_name='socialconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('shop', 'provider', 'page_id'), name='uq_social_connection_shop_provider_page_active'),
        ),
        migrations.AddIndex(
            model_name='productsocialpostlog',
            index=models.Index(fields=['shop', 'product', 'status'], name='socpost_shop_prod_status_ix'),
        ),
        migrations.AddIndex(
            model_name='productsocialpostlog',
            index=models.Index(fields=['connection', 'created_at'], name='social_post_conn_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='productsocialpostlog',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('shop', 'idempotency_key'), name='uq_social_post_shop_idempotency_active'),
        ),
    ]
