# Generated by Django 6.0.4 on 2026-07-15 06:28

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_setup_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='INBOUND', max_length=8)),
                ('text', models.TextField(blank=True, null=True)),
                ('attachment_payload', models.JSONField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('FACEBOOK', 'Facebook Messenger'), ('WEB_WIDGET', 'Web Widget'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('channel_identity', models.CharField(db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('FAQ', 'FAQ'), ('RETURN_POLICY', 'Return Policy'), ('SHIPPING_POLICY', 'Shipping Policy'), ('TERMS_OF_SERVICE', 'Terms of Service'), ('CUSTOM', 'Custom')], db_index=True, default='FAQ', max_length=20)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('vector_status', models.CharField(choices=[('PENDING', 'Pending'), ('CREATED', 'Created'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
