# Generated by Django 6.0.4 on 2026-07-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_entries', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['shop', 'channel', 'channel_identity'], name='conv_shop_chan_id_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'timestamp'], name='chatmsg_conv_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='chatmsg_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='faqentry',
            index=models.Index(fields=['shop', 'is_active', 'sort_order'], name='chat_faq_shop_active_order_idx'),
        ),
    ]
