# Generated by Django 6.0.4 on 2026-07-16 16:43

from django.db import migrations, models


def dedupe_live_conversations(apps, schema_editor):
    """
    Collapse any pre-existing duplicate LIVE conversations so the partial
    unique constraint below can be applied. For each
    (shop, channel, channel_identity) group with >1 non-deleted row, keep the
    oldest as the survivor, reassign the duplicates' messages to it, and
    soft-delete the duplicates.
    """
    Conversation = apps.get_model("chat", "Conversation")
    ChatMessage = apps.get_model("chat", "ChatMessage")
    from django.db.models import Count
    from django.utils import timezone

    dupe_keys = (
        Conversation.objects.filter(deleted_at__isnull=True)
        .values("shop_id", "channel", "channel_identity")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )

    now = timezone.now()
    for key in dupe_keys:
        rows = list(
            Conversation.objects.filter(
                deleted_at__isnull=True,
                shop_id=key["shop_id"],
                channel=key["channel"],
                channel_identity=key["channel_identity"],
            ).order_by("created_at")
        )
        survivor, duplicates = rows[0], rows[1:]
        dupe_ids = [c.id for c in duplicates]
        ChatMessage.objects.filter(conversation_id__in=dupe_ids).update(
            conversation_id=survivor.id
        )
        Conversation.objects.filter(id__in=dupe_ids).update(
            deleted_at=now, updated_at=now
        )


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_whatsappconfig'),
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(
            dedupe_live_conversations, reverse_code=migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('shop', 'channel', 'channel_identity'), name='uq_conversation_shop_channel_identity'),
        ),
    ]
