# Generated by Django 6.0.4 on 2026-07-17 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_conversation_unique_constraint'),
        ('identity', '0004_household_person_channelactor_contactpoint_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='identity.channelactor'),
        ),
    ]
