# Generated by Django 6.0.4 on 2026-07-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='has_unread',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='unread_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='access_token',
            field=models.TextField(),
        ),
    ]
