# Generated by Django 6.0.4 on 2026-07-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_unread_and_watoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='direction',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('SYSTEM', 'System')], default='INBOUND', max_length=8),
        ),
    ]
