# Generated by Django 6.0.4 on 2026-07-15 06:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opt_in_pooling', models.BooleanField(default=True, help_text='Contribute to and benefit from the global fraud pool.')),
                ('block_high_risk', models.BooleanField(default=False, help_text='Automatically block orders from high-risk numbers.')),
                ('warn_on_rto', models.BooleanField(default=True, help_text='Show warning in dashboard for customers with RTO history.')),
                ('rto_threshold', models.PositiveIntegerField(default=2, help_text='Number of RTOs before a customer is flagged as high-risk.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FraudEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_CANCELLED', 'Order Cancelled'), ('DELIVERY_FAILED', 'Delivery Failed'), ('FRAUD_REPORT_ADDED', 'Fraud Report Added')], max_length=30)),
                ('score_impact', models.IntegerField(default=0)),
                ('confidence_level', models.CharField(max_length=10)),
                ('source_type', models.CharField(choices=[('ACTOR', 'Actor'), ('PHONE', 'Phone')], max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraudProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('PHONE', 'Phone'), ('USER', 'User'), ('FACEBOOK', 'Facebook'), ('IP', 'IP Address')], max_length=20)),
                ('target_id', models.CharField(max_length=255)),
                ('risk_score', models.IntegerField(db_index=True, default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_id', models.UUIDField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('phone_hash', models.CharField(db_index=True, max_length=64)),
                ('reason', models.CharField(choices=[('RTO', 'Return To Origin (RTO)'), ('FAKE_ORDER', 'Fake Order / Prank'), ('HARASSMENT', 'Harassment'), ('UNPAID', 'Unpaid Advanced Fee')], max_length=20)),
                ('weight', models.IntegerField(default=10)),
                ('notes', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalFraudPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('rto_count', models.PositiveIntegerField(default=0)),
                ('fake_order_count', models.PositiveIntegerField(default=0)),
                ('harassment_count', models.PositiveIntegerField(default=0)),
                ('unpaid_count', models.PositiveIntegerField(default=0)),
                ('last_reported_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_reason', models.CharField(choices=[('SHARED_PHONE', 'Shared Phone'), ('SHARED_ADDRESS', 'Shared Address'), ('SHARED_IP', 'Shared IP')], max_length=30)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
