# Generated by Django 6.0.4 on 2026-07-15 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fraud', '0002_initial'),
        ('orders', '0002_initial'),
        ('shops', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudevent',
            name='phone_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_events', to='users.phoneidentity'),
        ),
        migrations.AddField(
            model_name='fraudprofile',
            name='phone_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_profiles', to='users.phoneidentity'),
        ),
        migrations.AddField(
            model_name='fraudevent',
            name='fraud_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fraud.fraudprofile'),
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_reports', to='orders.order'),
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='phone_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.phoneidentity'),
        ),
        migrations.AddField(
            model_name='fraudreport',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_reports', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='identitylink',
            name='user_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_links_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identitylink',
            name='user_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_links_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fraudprofile',
            index=models.Index(fields=['target_type', 'target_id'], name='fraud_target_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudprofile',
            index=models.Index(fields=['risk_score'], name='fraud_risk_score_idx'),
        ),
        migrations.AddConstraint(
            model_name='fraudprofile',
            constraint=models.UniqueConstraint(fields=('target_type', 'target_id'), name='uq_fraud_target'),
        ),
        migrations.AddIndex(
            model_name='fraudevent',
            index=models.Index(fields=['fraud_profile', 'created_at'], name='fraud_event_profile_time_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudevent',
            index=models.Index(fields=['actor', 'created_at'], name='fraud_event_actor_time_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudevent',
            index=models.Index(fields=['phone_identity', 'created_at'], name='fraud_event_phone_time_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudreport',
            index=models.Index(fields=['phone_hash'], name='fraud_phone_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudreport',
            index=models.Index(fields=['shop', 'reported_at'], name='fraud_shop_report_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudreport',
            index=models.Index(fields=['reported_at'], name='fraud_reported_at_idx'),
        ),
        migrations.AddIndex(
            model_name='identitylink',
            index=models.Index(fields=['user_a', 'user_b'], name='identity_link_users_idx'),
        ),
        migrations.AddConstraint(
            model_name='identitylink',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b', 'link_reason'), name='uq_identity_link'),
        ),
    ]
