# Generated by Django 6.0.4 on 2026-05-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0003_identity_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitylink',
            name='link_reason',
            field=models.CharField(choices=[('SHARED_PHONE', 'Shared Phone'), ('SHARED_ADDRESS', 'Shared Address'), ('SHARED_IP', 'Shared IP')], max_length=30),
        ),
    ]
