# Generated by Django 6.0.4 on 2026-07-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0004_unify_phone_hashing'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudreport',
            name='counts_toward_pool',
            field=models.BooleanField(default=False),
        ),
    ]
