# Generated by Django 6.0.4 on 2026-07-14 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('loyalty_points', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(db_index=True, max_length=100, unique=True)),
                ('custom_domain', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('grace_period_until', models.DateTimeField(blank=True, null=True)),
                ('override_max_products', models.IntegerField(blank=True, null=True)),
                ('override_max_staff', models.IntegerField(blank=True, null=True)),
                ('is_billing_exempt', models.BooleanField(default=False)),
                ('packaging_weight_grams', models.PositiveIntegerField(default=0, help_text="Added to every order's total weight for accurate courier billing")),
                ('base_currency', models.CharField(default='BDT', help_text='ISO 4217 currency code for this shop. All price fields inherit from this value — individual prices do not carry their own currency. Example: BDT, USD, EUR.', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_reservation_minutes', models.PositiveIntegerField(default=30)),
                ('allow_guest_checkout', models.BooleanField(default=True)),
                ('mandatory_advance_fee_bdt', models.PositiveIntegerField(default=0)),
                ('uses_platform_courier_credentials', models.BooleanField(default=False)),
                ('prepaid_misuse_consecutive_limit', models.PositiveSmallIntegerField(default=5)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('branding_slug_release_days', models.PositiveIntegerField(default=30)),
                ('ai_credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_balance_credits', models.PositiveIntegerField(default=0)),
                ('notification_targets', models.JSONField(blank=True, default=list)),
                ('show_stock_count', models.BooleanField(default=True)),
                ('enable_product_reviews', models.BooleanField(default=True)),
                ('tax_calculation_base', models.CharField(choices=[('ORIGINAL', 'Calculate Tax on Original Price'), ('DISCOUNTED', 'Calculate Tax on Discounted Price')], default='DISCOUNTED', max_length=20)),
                ('discount_application', models.CharField(choices=[('EXCLUSIVE', 'Discount is Exclusive of Tax'), ('INCLUSIVE', 'Discount is Inclusive of Tax')], default='EXCLUSIVE', max_length=20)),
                ('messenger_context_window_size', models.PositiveIntegerField(default=20)),
                ('messenger_human_takeover_ttl_minutes', models.PositiveIntegerField(default=30)),
                ('messenger_max_orders_per_psid_per_day', models.PositiveIntegerField(default=5)),
                ('messenger_order_draft_ttl_hours', models.PositiveIntegerField(default=24)),
                ('messenger_fallback_message', models.TextField(default="I'm having a little trouble right now. Our team will reach out to you shortly! 🙏")),
                ('messenger_greeting_keywords', models.JSONField(blank=True, default=list, help_text='Case-insensitive full-message greeting keywords that trigger an auto-welcome without using AI credits. Leave empty to use the system defaults.')),
                ('custom_domain_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('BRANCH', 'Retail Branch'), ('WAREHOUSE', 'Warehouse'), ('OFFICE', 'Corporate Office'), ('CUSTOMER_SERVICE', 'Customer Service Center')], default='BRANCH', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Stock Location',
                'verbose_name_plural': 'Stock Locations',
            },
        ),
        migrations.CreateModel(
            name='StoreTheme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme_id', models.CharField(choices=[('minimalist', 'Minimalist'), ('bold', 'Bold & Tech'), ('elegance', 'Soft Elegance'), ('urban', 'Urban Streetwear')], default='minimalist', max_length=50)),
                ('aesthetic_overrides', models.JSONField(blank=True, default=dict)),
                ('active_components', models.JSONField(blank=True, default=dict)),
                ('typography', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro'), ('BUSINESS', 'Business')], max_length=20, unique=True)),
                ('max_products', models.IntegerField(default=5)),
                ('max_staff', models.IntegerField(default=1)),
                ('can_use_pos', models.BooleanField(default=False)),
                ('can_use_api', models.BooleanField(default=False)),
                ('can_use_pixels', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShopMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('CASHIER', 'Cashier')], default='CASHIER', max_length=20)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='shops.shop')),
            ],
        ),
    ]
