# Generated by Django 6.0.4 on 2026-07-15 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shops.stocklocation'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='shopmember',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Primary location this member works at.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='shops.stocklocation'),
        ),
        migrations.AddField(
            model_name='storetheme',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='shops.subscriptionplan'),
        ),
        migrations.AddIndex(
            model_name='shopsettings',
            index=models.Index(fields=['shop', 'deleted_at'], name='shopsettings_shop_deleted_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('shop',), name='unique_default_location_per_shop'),
        ),
        migrations.AlterUniqueTogether(
            name='shopmember',
            unique_together={('user', 'shop')},
        ),
        migrations.AddIndex(
            model_name='storetheme',
            index=models.Index(fields=['shop', 'deleted_at'], name='storetheme_shop_deleted_idx'),
        ),
    ]
