# Generated by Django 6.0.4 on 2026-07-17 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_household_person_channelactor_contactpoint_person_and_more'),
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profiles', to='identity.person'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['shop', 'phone_number'], name='custprofile_shop_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['person'], name='custprofile_person_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('person__isnull', False)), fields=('shop', 'person'), name='uq_customer_profile_shop_person'),
        ),
    ]
