# Generated by Django 6.0.4 on 2026-05-02 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_merge_0008_prepaid_and_0010_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('BRANCH', 'Retail Branch'), ('WAREHOUSE', 'Warehouse'), ('OFFICE', 'Corporate Office'), ('CUSTOMER_SERVICE', 'Customer Service Center')], default='BRANCH', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shops.stocklocation')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Stock Location',
                'verbose_name_plural': 'Stock Locations',
            },
        ),
        migrations.AddField(
            model_name='shopmember',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Primary location this member works at.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='shops.stocklocation'),
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('shop',), name='unique_default_location_per_shop'),
        ),
    ]
