# Generated by Django 6.0.4 on 2026-07-15 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('mohajon_media', '0002_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='mohajon_media.media'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_media', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='shop',
            field=models.ForeignKey(db_index=False, help_text='Denormalized for RLS efficiency', on_delete=django.db.models.deletion.CASCADE, related_name='product_media_links', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_images', to='mohajon_media.media'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='shop',
            field=models.ForeignKey(db_index=False, help_text='Denormalized for RLS index efficiency', on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='shoptrackingconfig',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_config', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='shops.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='catalog.productvariant'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'parent'], name='category_shop_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'sort_order'], name='category_shop_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('shop', 'slug'), name='uq_category_shop_slug_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'status'], name='product_shop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'sort_order'], name='product_shop_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('status', 'SCHEDULED')), fields=['status', 'publish_at'], name='product_scheduled_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['search_vector'], name='product_search_vector_gin_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('shop', 'slug'), name='uq_product_shop_slug_active'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('sku__gt', '')), fields=('shop', 'sku'), name='uq_product_shop_sku_active'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['product', 'sort_order'], name='productmedia_product_sort_idx'),
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_thumbnail', True)), fields=('product',), name='uq_productmedia_one_thumbnail'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'product'], name='variant_shop_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('sku__gt', '')), fields=['shop', 'sku'], name='variant_shop_sku_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('sku__gt', '')), fields=('shop', 'sku'), name='uq_variant_shop_sku_active'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['shop', 'variant', 'created_at'], name='invlog_shop_var_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['shop', 'created_at'], name='invlog_shop_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrecord',
            index=models.Index(fields=['shop', 'location'], name='stock_shop_loc_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('variant', 'location'), name='uq_variant_per_location'),
        ),
    ]
