# Generated by Django 6.0.4 on 2026-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vector_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CREATED', 'Created'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
