# Generated by Django 6.0.4 on 2026-07-24 04:53
# Manually amended: null out stale 1536-dim embeddings before resize so
# Postgres does not reject the ALTER COLUMN TYPE with a dimension mismatch.
# Records are reset to PENDING so the Celery worker re-embeds them at 3072-dim.

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_initial'),
    ]

    operations = [
        # Step 1: clear stale 1536-dim vectors — must happen before the
        # column type is altered, otherwise Postgres raises DataException.
        migrations.RunSQL(
            sql="""
                UPDATE catalog_product
                SET embedding = NULL, vector_status = 'PENDING'
                WHERE embedding IS NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: resize the column to 3072 dimensions (gemini-embedding-2).
        migrations.AlterField(
            model_name='product',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
