# Generated by Django 6.0.4 on 2026-07-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('usage_type', models.CharField(choices=[('CHAT_COMPLETION', 'Chat Completion'), ('EMBEDDING', 'Embedding'), ('IMAGE_GENERATION', 'Image Generation')], db_index=True, max_length=32)),
                ('provider', models.CharField(choices=[('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic'), ('STABILITY', 'Stability AI'), ('CUSTOM', 'Custom')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('usd_cost', models.DecimalField(decimal_places=8, default=0, max_digits=14)),
                ('credits_deducted', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('usage', models.CharField(choices=[('CHAT_COMPLETION', 'Chat Completion'), ('EMBEDDING', 'Embedding'), ('IMAGE_GENERATION', 'Image Generation')], db_index=True, max_length=32)),
                ('provider', models.CharField(choices=[('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic'), ('STABILITY', 'Stability AI'), ('CUSTOM', 'Custom')], default='OPENAI', max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('input_price_per_1m_tokens', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('output_price_per_1m_tokens', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('image_price_per_call', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['usage', 'priority', 'model_name'],
                'indexes': [models.Index(fields=['usage', 'is_active', 'priority'], name='ai_model_usage_active_pri_idx'), models.Index(fields=['provider', 'usage'], name='ai_model_provider_usage_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('usage', 'provider', 'model_name'), name='uq_ai_model_usage_provider_model_active'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('usage',), name='uq_ai_model_single_default_per_usage')],
            },
        ),
    ]
