# Generated by Django 6.0.4 on 2026-07-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['shop', 'created_at'], name='ai_usage_shop_created_idx'),
        ),
    ]
