# Generated by Django 6.0.4 on 2026-07-22 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
        ('billing', '0003_initial'),
        ('shops', '0003_customerprofile_person_customerprofile_shop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICreditLot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('PURCHASED', 'Purchased'), ('BONUS', 'Bonus'), ('PROMOTION', 'Promotion'), ('REFERRAL', 'Referral'), ('ADJUSTMENT', 'Manual Adjustment')], db_index=True, max_length=20)),
                ('credits_granted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credits_remaining', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_exhausted', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_ai_credit_lots', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_credit_lots', to='shops.shop')),
                ('source_topup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_lots', to='billing.aicredittopup')),
            ],
            options={
                'ordering': ['expires_at', 'created_at'],
                'indexes': [models.Index(fields=['shop', 'is_expired', 'is_exhausted', 'expires_at'], name='ai_credit_lot_active_idx')],
            },
        ),
    ]
