# Generated by Django 6.0.4 on 2026-07-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_seed_legacy_credit_lots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelregistry',
            name='provider',
            field=models.CharField(choices=[('OPENAI', 'OpenAI'), ('GOOGLE', 'Google'), ('ANTHROPIC', 'Anthropic'), ('STABILITY', 'Stability AI'), ('CUSTOM', 'Custom')], default='OPENAI', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='provider',
            field=models.CharField(choices=[('OPENAI', 'OpenAI'), ('GOOGLE', 'Google'), ('ANTHROPIC', 'Anthropic'), ('STABILITY', 'Stability AI'), ('CUSTOM', 'Custom')], max_length=20),
        ),
    ]
