# Generated by Django 6.0.4 on 2026-07-14 05:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=512)),
                ('s3_key', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('cdn_url', models.URLField(blank=True, max_length=2048)),
                ('md5_hash', models.CharField(blank=True, db_index=True, max_length=32)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=127)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
    ]
