# Generated by Django 6.0.4 on 2026-07-15 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mohajon_media', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'created_at'], name='media_shop_created_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['s3_key'], name='media_s3key_active_idx'),
        ),
    ]
