# Generated by Django 6.0.4 on 2026-07-17 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_remove_courierconsignment_courier_shop_stat_cr_ix_and_more'),
        ('shops', '0003_customerprofile_person_customerprofile_shop_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CourierConsignment',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('provider', models.CharField(choices=[('PATHAO', 'Pathao'), ('PAPERFLY', 'Paperfly'), ('STEADFAST', 'Steadfast'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                        ('external_consignment_id', models.CharField(max_length=120)),
                        ('tracking_code', models.CharField(blank=True, max_length=120)),
                        ('status', models.CharField(choices=[('CREATED', 'Created'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RTO', 'Return To Origin')], default='CREATED', max_length=20)),
                        ('payload', models.JSONField(blank=True, default=dict)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to='orders.order')),
                        ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_consignments', to='shops.shop')),
                    ],
                    options={
                        'db_table': 'orders_courierconsignment',
                        'indexes': [models.Index(fields=['shop', 'status', 'created_at'], name='courier_shop_stat_cr_ix'), models.Index(fields=['provider', 'external_consignment_id'], name='courier_prov_ext_idx')],
                        'constraints': [models.UniqueConstraint(fields=('provider', 'external_consignment_id'), name='uq_courier_provider_extid')],
                    },
                ),
            ],
            database_operations=[]
        )
    ]
