# Generated by Django 6.0.4 on 2026-07-18 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
        ('shops', '0003_customerprofile_person_customerprofile_shop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that owns this record')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('PATHAO', 'Pathao'), ('PAPERFLY', 'Paperfly'), ('STEADFAST', 'Steadfast'), ('OTHER', 'Other')], max_length=20)),
                ('credentials_encrypted', models.TextField(blank=True, help_text='JSON-encoded courier credentials stored encrypted. Use shipping.services.set_courier_credentials() to write — never write directly.')),
                ('default_store_id', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Merchant can disable a courier without deleting its credentials.')),
                ('is_test_mode', models.BooleanField(default=False, help_text='Toggles the courier client to its sandbox environment.')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_accounts', to='shops.shop')),
            ],
            options={
                'db_table': 'shipping_courieraccount',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['shop', 'is_active'], name='courier_acct_shop_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('shop', 'provider'), name='uq_courier_account_shop_provider')],
            },
        ),
    ]
