# Generated by Django 6.0.4 on 2026-07-15 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_initial'),
        ('orders', '0002_initial'),
        ('shops', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='users.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shops.customerprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.phoneidentity'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='users.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courierconsignment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='orderrefundevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_refund_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderrefundevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_events', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderrefundevent',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_refund_events', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='ordersplitlink',
            name='child_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_links_as_child', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordersplitlink',
            name='parent_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_links_as_parent', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordertransitionlog',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordertransitionlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoices', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoices', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shop', 'status', 'created_at'], name='order_shop_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='order_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone_identity', 'created_at'], name='order_phone_created_idx'),
        ),
        migrations.AddIndex(
            model_name='courierconsignment',
            index=models.Index(fields=['shop', 'status', 'created_at'], name='courier_shop_stat_cr_ix'),
        ),
        migrations.AddIndex(
            model_name='courierconsignment',
            index=models.Index(fields=['provider', 'external_consignment_id'], name='courier_prov_ext_idx'),
        ),
        migrations.AddConstraint(
            model_name='courierconsignment',
            constraint=models.UniqueConstraint(fields=('provider', 'external_consignment_id'), name='uq_courier_provider_extid'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'created_at'], name='orderitem_order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrefundevent',
            index=models.Index(fields=['shop', 'order', 'created_at'], name='ordrefund_shop_ord_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrefundevent',
            index=models.Index(fields=['shop', 'status', 'created_at'], name='ordrefund_shop_st_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='ordersplitlink',
            index=models.Index(fields=['parent_order', 'created_at'], name='ordsplit_parent_created_ix'),
        ),
        migrations.AddIndex(
            model_name='ordersplitlink',
            index=models.Index(fields=['child_order', 'created_at'], name='ordsplit_child_created_ix'),
        ),
        migrations.AddIndex(
            model_name='ordertransitionlog',
            index=models.Index(fields=['order', 'created_at'], name='ordtrans_order_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinvoice',
            index=models.Index(fields=['shop', 'expires_at', 'is_used'], name='invoice_shop_expiry_used_idx'),
        ),
    ]
