# Generated by Django 6.0.4 on 2026-07-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='courierconsignment',
                    name='courier_shop_stat_cr_ix',
                ),
                migrations.RemoveIndex(
                    model_name='courierconsignment',
                    name='courier_prov_ext_idx',
                ),
                migrations.RemoveConstraint(
                    model_name='courierconsignment',
                    name='uq_courier_provider_extid',
                ),
                migrations.DeleteModel(
                    name='CourierConsignment',
                ),
            ],
            database_operations=[],
        )
    ]
