# Generated by Django 6.0.4 on 2026-05-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_fraud_identity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='verification_method',
            field=models.CharField(choices=[('OTP', 'OTP Verification'), ('CALL', 'Phone Call Verification'), ('SOCIAL', 'Social Media Auto-Verification'), ('COURIER', 'Courier Confirmation'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
