# Generated by Django 6.0.4 on 2026-07-14 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadletterevent',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letter_events', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='notificationdeliverylog',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_delivery_logs', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='shops.shop'),
        ),
    ]
