# Generated by Django 6.0.4 on 2026-07-15 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['shop', 'status', 'created_at'], name='notif_shop_status_created_ix'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('shop', 'user', 'event_key'), name='uq_notif_pref_shop_user_event_active'),
        ),
    ]
